# imports

# variables
displayInfo = True
# iso = ...
# shutterSpeed = ...
# awbMode = ...
# fileFormat = ...
# imageEffect = ...
# wbRedGain = ...
# wbBlueGain = ...
# captureMode (photo, video, time lapse...) = ...
# resolution = ... (might have to be split into two lists or more for photo, video etc...
# fullScreen = True ('False' makes the screen windowed at pi display resolution)

settings = ("variable1", "variable2", "...")
currentSettingIndexInt = 0

print(settings[currentSettingIndexInt])  # <<< it works.

# classes

# functions

# pygame setup

# main game loop
